import type { Metadata } from "next";
import { IM_Fell_English } from "next/font/google";
import "./globals.css";

const imFell = IM_Fell_English({
  weight: ["400"],
  subsets: ["latin"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={"h-full antialiased"}
    >
      <body className={`min-h-full flex flex-col ${imFell.className}`}>{children}</body>
    </html>
  );
}
